apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubs-demo-deployment
  labels:
    app: react-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-container
          image: ozamudazai/kuber-demo
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: kuber-service
spec:
  selector:
    app.kubernetes.io/name: react-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
